remote_theme: pages-themes/midnight@v0.2.0
title: Chris Wei's Blog
description: A practice blog site for Udemy ChatGpt Course
show_downloads: "false"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one