title: Chris Wei
description: IT Engineer
site_title: 'Bl@g - Chris Wei'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://yujyewei.github.io/yujyeblog/
email: yujyew@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/profile.jpg

# Google Analytics ID
google_analytics: 